name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull swest152/amazonwebapp:latest
      - name: Delete Old docker container
        run: sudo docker rm -f swest152/amazonwebapp || true
      - name: Run Docker Container
        run: sudo docker run -p 80:8080 swest152/amazonwebapp