name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build Spring Boot App
      run: ./gradlew build
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      #remove references to name
      run: docker build --build-arg JAR_FILE=build/libs/\*.jar -t ${{secrets.DOCKER_USERNAME}}/amazonwebapp .
    - name: Push to Dockerhub
      run: docker push ${{secrets.DOCKER_USERNAME}}/amazonwebapp
